### ISSUE TITLE
Add an icon library

### ISSUE THREAD

**Issue by mapsam** [cybersea/efh2016-metrics#18]
Iconography is helpful for UIs, especially for form interactions (i.e. checkmarks). Let's look at adding [fontawesome](http://fontawesome.io/) or something similar.

**Comment by cybersea** [comment]
I previously downloaded a fontawesome zip file (v. 4.6.3), but am not sure how to deploy it as part of my app.   If you want to give me some tips, I can likely get that done myself.

**Comment by mapsam** [comment]
Nice! I added a link to the CDN in https://github.com/cybersea/efh2016-metrics/commit/832eabf053d2b05bcf3e342fb7dd01ef9e8126f4 but remember you saying you'd like to be able work offline, so downloading the pack and adding to this repo would be a good next step.

**Comment by cybersea** [comment]
I added a local version of Font Awesome in 9466179c8701037e17747b001a5d13ec101a65aa

**Comment by mapsam** [comment]
Woo!
