### ISSUE TITLE
Add Conservation Index

### ISSUE THREAD

**Issue by cybersea** [cybersea/efh2016-metrics#28]

**Comment by cybersea** [comment]
More complex calcs than simple sum required for summary table.   Need to average each individual underlying metric by grid cell, and then average that.

**Comment by mapsam** [comment]
Let's look into refactoring how the tables are built as well, so adding more calculations is more intuitive. #31

**Comment by cybersea** [comment]
Added Conservation Value metrics to polygon table, but not summary table.  Commit cbd639eb625c7ebb02d306f91bec0d6544348955
