### ISSUE TITLE
UI approach to select an entire proposal

### ISSUE THREAD

**Issue by cybersea** [cybersea/efh2016-metrics#3]

**Comment by cybersea** [comment]
@mapsam, the buttons are there, but I could use your help making them look good and coming up with an intuitive UI.    

I realize after our first draft, that maybe we need two buttons -- one to select a full proposal and one to remove the proposal from the selected set.    Or, maybe it should be two pull-down menu with all the proposals listed?     

Here is the reason -- There may be some interactive selections and deselections of individual polygons from that proposal that occur after selecting a full proposal.  So, we don't necessarily know if they want to add the rest of the polygons to the current selection or remove the remaining polygons from the current selection.

What are your thoughts?

I can work on fixing the functionality (which is described in Issue #15 )

**Comment by cybersea** [comment]
I added placeholder buttons and added/fixed functionality for selecting and unselecting all polygons in a proposal.  See commit 0ef11982543ddc81fa7fd738dc995f7f9412429d

**Comment by mapsam** [comment]
@cybersea good thinking - having a select/unselect all is a helpful UI boost. I'll 🤔 through some ways to make this clear.

I've often add ["tooltips"](http://www.menucool.com/tooltip/css-tooltip) for things like this. I'm not a fan of completely relying on them, but when space gets tight, it helps orient the user without them having to experiment with the functionality.

**Comment by cybersea** [comment]
Sounds great.  I do like the tool tips on Drop n Chop

**Comment by cybersea** [comment]
See Pull Request:  https://github.com/cybersea/efh2016-metrics/pull/33

This is awesome @mapsam
