### ISSUE TITLE
Visually delineate full alternatives from additional polygons

### ISSUE THREAD

**Issue by cybersea** [cybersea/efh2016-metrics#35]
@mapsam -- you were right.  I think it would be helpful to delineate the two sets of polygons.  The top two are EFH Alternatives, and the bottom ones are Other Proposals.  Let me know if this is something you have time for, or can give me hints to do it myself.

**Comment by mapsam** [comment]
@cybersea I think you should be able to add headers/paragraphs/whatever-you-like in between the labels and the inputs of the next proposal [here](https://github.com/cybersea/efh2016-metrics/blob/779d5cd21d0841c2fbb89cd0980a316ad9db9c60/index.html#L79). This would look like:

``` html
<p class="proposal-type-class">Lettered Proposals</p>
<input>
<label>Proposal A</label>
<input>
<label>Proposal B</label>

<p class="proposal-type-class">Numbered Proposals</p>
<input>
<label>Proposal 1</label>
<input>
<label>Proposal 2</label>
<input>
<label>Proposal 3</label>
```

**Comment by cybersea** [comment]
Thanks!
