### ISSUE TITLE
Create Tabs on Left Side panel for Summary Table and Detailed Table for Download

### ISSUE THREAD

**Issue by cybersea** [cybersea/efh2016-metrics#4]
one tab will have the current summary metrics table and the second tab will have a list of the metrics for each selected area.  Kind of like on the right side of http://geojson.io/

The general table structure can be seen [here](https://docs.google.com/spreadsheets/d/1rWjcIVAe0rGJm9Hvb1_xGkfrmMrA3bmtaHef4yymfRI/edit?usp=sharing)

Ideally, the detailed table will be available to be downloaded to a csv file or spreadsheet.

**Comment by rgdonohue** [comment]
Got the basic structure and functionality in there. Currently toggling the visibility of the two panels. Lost of room for aesthetic refinement.

**Comment by cybersea** [comment]
Thanks!
