### ISSUE TITLE
Change Layer Switcher from Leaflet to Basic JavaScript object

### ISSUE THREAD

**Issue by cybersea** [cybersea/efh2016-metrics#5]
This will facilitate other functions, like unselecting areas when the layer is turned off.  Will also potentially allow a more complex UI with different sections for proposals and ancillary layers when they get added.  Perhaps a collapsible/tree-like view, with the legend integrated?

**Comment by rgdonohue** [comment]
Currently the method in the buildUI() function detected change and stores value as local var. values are the Leaflet GeoJson layers.

**Comment by cybersea** [comment]
Awesome.  Thank you!
